### ISSUE TITLE
[remove] 刪除檔案是否可以一個以上？

### ISSUE THREAD

**Issue by anna-luyufeng** [DaydreamLab/media#3]
刪除的單位可以為資料夾或是檔案對嗎？

**Comment by ppuff1988** [comment]
刪除的輸入鍵值有改變請見:
https://documenter.getpostman.com/view/2664518/RWgwSwMp
如果要刪除的資料夾  請填入dir後，names請給我[]

**Comment by ppuff1988** [comment]
請填入檔名跟資料夾名稱即可
不用給我[]

**Comment by anna-luyufeng** [comment]
請問改成給檔案路徑 path 的值？

**Comment by ppuff1988** [comment]
對 
dir 是路徑
names[]   放檔名或資料夾名稱

**Comment by ppuff1988** [comment]
請更新
送dirs[]給我
